name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=iac init

      - name: Terraform Validate
        run: terraform -chdir=iac validate

      - name: Terraform Plan
        run: terraform -chdir=iac plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform -chdir=iac apply -auto-approve -var-file="terraform.tfvars"
        env:
          AWS_ACCESS_KEY_ID: AKIAZLYD32DA4DZ6LQ5S
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: us-east-1
